### ISSUE TITLE
Game Theory for IT Transformation && Making Work Visible to Leadership 

### ISSUE THREAD

**Issue by jjasghar** [Austin-Devops/talks#1]
# Title
Game Theory for IT Transformation && Making Work Visible to Leadership 

# Abstract

As organizations begin the process of digitally transforming they will often struggle after initial efforts at automation (the dreaded J-curve). In this 40 minute session we'll discuss why the J-curve phenomenon occurs and define the concept behind the Pareto Inefficient Nash Equilibrium through a game show called "Golden Balls". In this entertaining segment we'll discuss how you can introduce this concept to effectively change the game and push past the low-end of the J-curve.

The journey doesn’t end there, as organizations begin shipping changes more often, introducing new features, services, and dependencies complexity begins to rise. This often results in teams forming centers of excellence around reliability and availability. We will talk about how Site Reliability Engineers enable organizations by accelerating into the upper end of the J-curve through leveraging observability to effectively establish error budgets, SLOs and SLIs. We’ll discuss how SRE teams can leverage distributed tracing aggregates, system metrics, and log analytics to effectively measure “all the things” and the value this measurement brings to engineering teams through visibility, communication, and accountability.

Slides: https://drive.google.com/file/d/1lWgIVTlyyOyHturs04mU7PpriM9hN46J/view (video redacted due to size)

# Requested Date

March 9th 2020

# Bio

Kevin works for Instana, a managed service provider that specializes in observability and monitoring production systems, as a Senior DevOps Advocate. He has traveled the globe speaking on topics including DevOps, Docker, Observability, and Culture Transformation at conferences and such as DockerCon, SREcon, Open Source Summit EU/US, Velocity and DevOpsDays including Tokyo and Houston. He is passionate about educating engineers about the benefits of observability, distributed tracing, and control theory.

In addition to his work at Instana, Kevin is the founder and core organizer for the local Docker meetup in Nashville and was the lead organizer for DevOpsDays Nashville in 2019. He has been distinguished by his peers as a Docker Captain for his work both professionally and within the DevOps community. He has been working in software development roles almost his entire career and enjoys learning about how fellow peers are leveraging modern practices and tooling.

At his previous jobs Kevin was responsible for designing and building distributed scheduling systems utilizing Amazon SQS, DynamoDB, Kinesis and Redshift. His most recent project he was responsible for a modern software delivery platform using Go/Angular which was integrated with Docker Swarm and Gitlab. This application is capable of delivering phoenix environments and a fully configurable production pipeline. This application manages the SDLC of over 1000 containers and dozens of engineers building on a Kafka, Cassandra, and Spring Boot ecosystem.

# Anything else?

Instana will be our food and beverage sponsor for the evening.

**Comment by behemphi** [comment]
Alas, Kevin left Instana, so this is dead for now.
