### ISSUE TITLE
Making Work Visible to Leadership

### ISSUE THREAD

**Issue by jjasghar** [Austin-Devops/talks#2]
# Title
Making Work Visible to Leadership

# Abstract

We do great things to prevent performance issues in the platforms for which we are responsible. We recognize problems weeks before they affect customers and we remedy them.

The better we do our jobs, the less it appears we do our jobs.

This short talk provides some ideas to manage up and across to make your work visible.

# Requested Date

March 9th, 2020

# Bio

Boyd Hemphill is a DevOps raconteur in the silicon hills of Austin Texas. Boyd founded and organizes the Austin DevOps Meetup. He privileged to serve as part of the DevOps Days Austin Organizers team. In his professional life, Boyd has been a developer (PL/SQL, PHP), DBA (Oracle and MySQL), and system administrator as well as a Director and even a CTO. Today he is the Director of Cloud Engineering for Contrast Security we we are making the internet just a bit safer.

# Anything else?

Nope.

**Comment by behemphi** [comment]
Done!
