### ISSUE TITLE
Quantum Computing From Scratch

### ISSUE THREAD

**Issue by egonczeruk** [Austin-Devops/talks#5]
# Title

Quantum Computing From Scratch

# Abstract

Curious about quantum computing? Intrigued about entanglement? Come learn the basics in a 1-hour crash course!

Quantum computing is a radical paradigm change from "classical" computing, but it rests on a few surprisingly simple principles.  In this talk we will take a bottom-up approach to quantum computing.  Starting with a basic mathematical model, we will slowly build our way up to an understanding of quantum ideas such as superposition, entanglement, and teleportation.  These concepts will be used to construct a quantum circuit that beats classical computers, demonstrating quantum supremacy from scratch.  As a first introduction to quantum computing, we will do our best to stay close to the pure mathematics and avoid any hand-waving about the famously "spooky" quantum phenomena.  The goal is to have a clear understanding of quantum computing through math rather than metaphor.  

By the end, you will understand qubits, entanglement, and superposition through their simple mathematical descriptions.  You will be able to use these concepts to write the truly quantum algorithm for teleportation.

# Requested Date

April 13th, 2020

# Bio

Thomas is a creative coder, pragmatic automater, and cloud engineer at Google. He's an avid evangelist of tech & part-time teacher with a penchant for making difficult topics accessible to amateurs

**Comment by jjasghar** [comment]
We may need a longer bio...i don't actually know our policy here. @nimbinatus thoughts?

**Comment by nimbinatus** [comment]
Yeah, I kinda like a bit more of a standard bio so people can get a sense of background and such.

cc: @behemphi

**Comment by egonczeruk** [comment]
Updated - LMK if this work. Thanks!

**Comment by behemphi** [comment]
https://www.meetup.com/austin-devops/events/270023508/?isFirstPublish=true
