### ISSUE TITLE
Sticking Together while Staying Apart: Resilience in the Time of Global Pandemic

### ISSUE THREAD

**Issue by crayzeigh** [Austin-Devops/talks#7]
# Title

Sticking Together while Staying Apart: Resilience in the Time of Global Pandemic

# Abstract

Everything is a little bit broken all of the time. Sometimes, like recently, as in right now, the core truths and assumptions about the universe seem to be shifted out from underneath us without warning. And yet, Netflix streams movies, GitHub serves code, we all keep going and working from home and surviving. These systems, both technical and social, are resilient. And through their resilience they are able to handle all those one-in-a-million occurrences that crop up nine-times-in-ten. But what does it mean to be resilient? And further, how can we recognize and grow this resilience to better deal with the systemic surprises we’re dealing with right now and in the future? What does a resilient team look like, and how do you foster that?

This talk will answer:  

- What is Resilience?
- How can we create resilience in ourselves, teams and systems?
- How do our networks of systems (people, teams, organizations, applications) create resilience for each other?
- What happens when major systems and networks fail?
- How can we discover and foster resilience in our people, teams and systems?

# Requested Date

Whichever one you said ;). I think this is for Tuesday, 8 Sept

# Bio

Aaron Aldrich is a Founding organizer of DevOpsDays Hartford, and frequent DevOpsDays organizer and participant all over. When not talking about DevOps and Resilience Engineering, you can find him talking about Mental Health with osmihelp.org or running Emotional Intelligence workshops with EmotionalAPI.com. Find him on twitter @crayzeigh for general nonsense and tomfoolery.

# Anything else?

I don't think so?

**Comment by nimbinatus** [comment]
Done and given!
