### ISSUE TITLE
Prevent Heroism: How to Work Today to Reduce Work Tomorrow

### ISSUE THREAD

**Issue by quintessence** [Austin-Devops/talks#9]
# Title 

Prevent Heroism: How to Work Today to Reduce Work Tomorrow

# Abstract

Reactive work is a massive time and value sink, but unfortunately existing gaps in team structure and/or metrics don’t capture “what’s missing”. For example, how do you track calls not placed, outages that never occurred? Traditional structures and metrics don’t necessarily capture this shift, yet everyone benefits from a better user experience - i.e. the unplaced call or outage. In this talk I’m going to discuss:

* Level set: explain the concept “upstream work”, as defined by Dan Heath in his book Upstream
* Explain why this focus is important
* Discuss how teams can start to shift from reactive work to proactive work, i.e. move upstream; including shifting reward structures away from Heroes
* Cover how to use metrics to support this shift in practice

# Requested Date

After mid-October please :) 

# Bio

Quintessence has worked in the IT community for over 10 years, including as a database administrator and a DevOps / Cloud / Infrastructure engineer. She was a core contributor to Stark & Wayne's SHIELD project, which adds backup functionality to Cloud Foundry, as well as a technical reviewer for Learning Go Programming published by Packt Publishing. Currently she is a Developer Advocate for PagerDuty, focusing community engagement related to DevOps. Outside of work she co-founded Inclusive Tech Buffalo and is a mentor to underrepresented minorities in tech so they can launch sustainable careers in development.

# Anything else?

Looking forward to speaking with your group! Feel free to DM me on the DevRel Slack or email me at quintessence@pagerduty.com if anything else is needed.

**Comment by nimbinatus** [comment]
And given! Thanks!
